#!/usr/bin/expect -f
set host [lindex $argv 0]
set user [lindex $argv 1]
set password [lindex $argv 2]
set commands [lrange $argv 3 $argc-1]
set timeout -1
spawn ssh $user@$host $commands
match_max 100000

expect {
    "*yes/no*"
    {
        send -- "yes\n"
    }
    "*assword*"
    {
        send -- "$password\n"
    }
    "*passphrase*"
    {
        send -- "$password\n"
    }
    "continue connecting"
    {
        send -- "yes\n"
    }
}

interact
